version: '3'
services:
  client01:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    container_name: client01
    environment:
      - cluster.name=mappy-cluster
      - node.name=client01
      - node.data=false
      - node.master=false
      - node.ingest=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=master03,data01,data02,data03,data04,master01,master02"
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - esnet
  data01:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    container_name: data01
    environment:
      - cluster.name=mappy-cluster
      - node.name=data01
      - node.data=true
      - node.master=false
      - node.ingest=false
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=master03,data04,data02,data03,client01,master01,master02"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    networks:
      - esnet
    ports:
      - 9211:9200
      - 9311:9300
  data02:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    container_name: data02
    environment:
      - cluster.name=mappy-cluster
      - node.name=data02
      - node.data=true
      - node.master=false
      - node.ingest=false
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=master03,data01,data04,data03,client01,master01,master02"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata2:/usr/share/elasticsearch/data
    networks:
      - esnet
    ports:
      - 9212:9200
      - 9312:9300
  data03:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    container_name: data03
    environment:
      - cluster.name=mappy-cluster
      - node.name=data03
      - node.data=true
      - node.master=false
      - node.ingest=false
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=master03,data01,data02,data04,client01,master01,master02"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata3:/usr/share/elasticsearch/data
    networks:
      - esnet
    ports:
      - 9213:9200
      - 9313:9300
  data04:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    container_name: data04
    environment:
      - cluster.name=mappy-cluster
      - node.name=data04
      - node.data=true
      - node.master=false
      - node.ingest=false
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=master03,data01,data02,data03,client01,master01,master02"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata4:/usr/share/elasticsearch/data
    networks:
      - esnet
    ports:
      - 9214:9200
      - 9314:9300
  master01:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    container_name: master01
    environment:
      - cluster.name=mappy-cluster
      - node.name=master01
      - node.data=false
      - node.master=true
      - node.ingest=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - "discovery.zen.ping.unicast.hosts=data01, data02, data03, data04, client01, master03, master02"
    networks:
      - esnet
    ports:
      - 9201:9200
      - 9301:9300

  master02:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    container_name: master02
    environment:
      - cluster.name=mappy-cluster
      - node.name=master02
      - node.data=false
      - node.master=true
      - node.ingest=false
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=data01, data02, data03, data04, client01, master01, master03"
    networks:
      - esnet
    ports:
      - 9202:9200
      - 9302:9300
  master03:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    container_name: master03
    environment:
      - cluster.name=mappy-cluster
      - node.name=master03
      - node.data=false
      - node.master=true
      - node.ingest=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - "discovery.zen.ping.unicast.hosts=data01, data02, data03, data04, client01, master01, master02"
    networks:
      - esnet
    ports:
      - 9203:9200
      - 9303:9300

volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local
  esdata3:
    driver: local
  esdata4:
    driver: local

networks:
  esnet:
